const categories = [
    "Web Development",
    "Mobile App",
    "Data Science",
    "Machine Learning",
    "AI",
    "Game Dev",
    "Blockchain",
    "Cybersecurity",
    "IoT",
    "Automation",
    "UI UX",
    "Open Source",
    "Cloud",
    "Desktop App",
    "API Dev",
    "Tools",
    "Others",
];

const subcategoryMap = {
    "Web Development": [
        "Frontend",
        "Backend",
        "Full Stack",
        "JAMstack",
        "Static Sites",
        "CMS-Based",
        "Others",
    ],
    "Mobile App": [
        "Android",
        "iOS",
        "Cross Platform",
        "Flutter",
        "React Native",
        "Native Apps",
        "Others",
    ],
    "Data Science": [
        "Data Analysis",
        "Data Visualization",
        "ETL",
        "Data Cleaning",
        "Statistics",
        "Big Data",
        "Others",
    ],
    "Machine Learning": [
        "Supervised",
        "Unsupervised",
        "Reinforcement",
        "Model Deployment",
        "Model Evaluation",
        "ML Ops",
        "Others",
    ],
    AI: [
        "NLP",
        "Computer Vision",
        "Generative AI",
        "Expert Systems",
        "AI Ethics",
        "Search Algorithms",
        "Others",
    ],
    "Game Dev": [
        "2D Games",
        "3D Games",
        "Unity",
        "Unreal",
        "Game Mechanics",
        "Multiplayer",
        "Others",
    ],
    Blockchain: [
        "Smart Contracts",
        "Ethereum",
        "Solana",
        "Web3.js",
        "Wallet Integration",
        "NFTs",
        "Others",
    ],
    Cybersecurity: [
        "Network Security",
        "Web Security",
        "Pentesting",
        "Malware Analysis",
        "Cryptography",
        "Incident Response",
        "Others",
    ],
    IoT: [
        "Home Automation",
        "Wearables",
        "Smart Devices",
        "IoT Protocols",
        "Edge Computing",
        "Sensors",
        "Others",
    ],
    Automation: [
        "Task Automation",
        "Scripting",
        "RPA",
        "DevOps CI/CD",
        "Testing Automation",
        "Cron Jobs",
        "Others",
    ],
    "UI UX": [
        "Wireframing",
        "Prototyping",
        "User Research",
        "Accessibility",
        "Visual Design",
        "Interaction Design",
        "Others",
    ],
    "Open Source": [
        "Contributions",
        "Documentation",
        "Issue Fixing",
        "Maintaining Projects",
        "Community Engagement",
        "Licensing",
        "Others",
    ],
    Cloud: [
        "AWS",
        "Azure",
        "Google Cloud",
        "DevOps",
        "Serverless",
        "Cloud Storage",
        "Others",
    ],
    "Desktop App": [
        "Electron",
        "JavaFX",
        "Qt",
        "C# WinForms",
        "WPF",
        "Tkinter",
        "Others",
    ],
    "API Dev": [
        "REST",
        "GraphQL",
        "gRPC",
        "Postman",
        "API Auth",
        "Rate Limiting",
        "Others",
    ],
    Tools: [
        "CLI Tools",
        "Browser Extensions",
        "Dev Tools",
        "Productivity",
        "VSCode Extensions",
        "Automation Scripts",
        "Others",
    ],
    Others: [
        "Miscellaneous",
        "Experimental",
        "One-off Projects",
        "Learning Projects",
        "Hackathon Demos",
        "Mini Projects",
        "Others",
    ],
};

export  default {categories , subcategoryMap}